version: '3.3'
services:
  db:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dev_db_folder:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
volumes:
  dev_db_folder: