version: '3.3'
services:
  db:
    image: postgres:15.0-alpine
    env_file:
      - .env
    volumes:
      - himzosch_db:/var/lib/postgresql/data
    networks:
      - himzosch_network
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_SERVE_STATIC_FILES: true
      RAILS_ENV: production
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    networks:
      - himzosch_network
volumes:
  himzosch_db:
    external:
      name: himzosch_db

networks:
  himzosch_network:
